TEL-5120: cleanup socket when disconnecting/close
team-telnyx/freeswitch pull request #133
Opened 2022-04-04 12:04 UTC by StefanYohansson

2022-04-18 16:30 UTC, dev-ryanc requested changes

2022-04-18 16:30 UTC, dev-ryanc commented on src/switch_rtp.c
> +	if (rtp_session->sock_input) {
Please check as well the rtp_session

2022-04-18 16:30 UTC, dev-ryanc commented on src/switch_rtp.c
> +			switch_socket_shutdown(sock_input, SWITCH_SHUTDOWN_READWRITE);
There is a scenario where sock_output points to the same address as sock_input. Shutting it down here will make sock_output points to garbage memory. You may need to check sock_output before destroying sock_input

2022-04-18 16:30 UTC, dev-ryanc commented on src/switch_rtp.c
> +				switch_socket_shutdown(sock_input, SWITCH_SHUTDOWN_READWRITE);
There is a scenario where sock_output points to the same address as sock_input. Shutting it down here will make sock_output points to garbage memory. You may need to check sock_output before destroying sock_input

2022-04-21 11:09 UTC, piotrgregor reviewed
The crash was at `zrtp_send_rtp_callback`. 
Are you not trying to fix the outcome instead of a root cause @StefanYohansson ? Isn't the root problem that zrtp callback gets called when socket is already closed (or in a malformed state, e.g. not started yet - notice it was called from `_send_and_resend_hello`)?
Maybe we should find out how to disable zrtp callback instead of fixing all the problems that will arise when callback hasn't been stopped properly?

2022-05-13 12:14 UTC, closed without merging