TEL-5749: Add profile parameter to `sofia count gateways`
team-telnyx/freeswitch pull request #217
Opened 2023-08-08 12:00 UTC by Elhodred

2023-08-08 14:43 UTC, Elhodred commented on src/mod/endpoints/mod_sofia/mod_sofia.c
> +				if (!strcasecmp(argv[1], profile->name) && sofia_test_pflag(profile, PFLAG_RUNNING)) {
done

2023-08-08 16:32 UTC, mishehu approved these changes

2023-08-08 16:36 UTC, minhtuan1407-telnyx approved these changes

2023-08-08 16:52 UTC, dev-ryanc requested changes

2023-08-09 11:45 UTC, dev-ryanc commented on src/mod/endpoints/mod_sofia/mod_sofia.c
> +			if ((argc > 1 && !strcasecmp(argv[1], profile->name) && sofia_test_pflag(profile, PFLAG_RUNNING))
Got it, I forgot there's existing parameter to count either the profile or gateway. The second parameter is for the profile name. Yes this change make sense to me

2023-08-09 11:45 UTC, dev-ryanc approved these changes

2023-08-21 14:39 UTC, merged