fix edge case that causes crash when unregistering
team-telnyx/freeswitch pull request #247
Opened 2024-01-31 18:32 UTC by Elhodred

2024-02-01 11:36 UTC, dev-ryanc requested changes

2024-02-01 11:36 UTC, dev-ryanc commented on src/mod/endpoints/mod_sofia/sofia_reg.c
> +			if (gateway_ptr->sofia_private) {
Move this on the statement below, it should be deleted during the state of `REG_STATE_DOWN`

2024-02-01 11:36 UTC, dev-ryanc commented on src/mod/endpoints/mod_sofia/sofia_reg.c
> +			if (gateway_ptr->nh) {
Move this on the statement below, it should be deleted during the state of REG_STATE_DOWN

2024-02-01 11:37 UTC, dev-ryanc commented
Make sure to run a sipp test on all possible scenario to make sure we don't introduce another crash

2024-02-02 12:37 UTC, dev-ryanc requested changes

2024-02-02 12:45 UTC, Elhodred commented on src/mod/endpoints/mod_sofia/sofia.c
> +	if (event == nua_r_unregister && status != 401 && status != 407 && status >= 200) {
so I can send it to the done section safely and the clean up stuff runs. Is what avoided the lock that was happening

2024-02-02 13:14 UTC, dev-ryanc requested changes

2024-02-02 13:14 UTC, dev-ryanc commented on src/mod/endpoints/mod_sofia/sofia.c
> +		if (gateway) {
Why can't we put this on the if condition above? It doesn't do anything if we don't have the gateway ptr

2024-02-02 14:32 UTC, dev-ryanc approved these changes

2024-02-02 23:40 UTC, merged