TEL-5929: set GW as SOFIA_GATEWAY_UP as soon as 200 OK is received for REGISTER
team-telnyx/freeswitch pull request #255
Opened 2024-02-12 15:55 UTC by Elhodred

2024-02-12 17:09 UTC, dev-ryanc commented
It will not fix the issue, the delay can also be when we will send out the REGISTER.

2024-02-12 17:09 UTC, dev-ryanc requested changes

2024-02-12 17:09 UTC, dev-ryanc commented on src/mod/endpoints/mod_sofia/sofia.c
> +			// GWs are parsed each time we add/remove a GW. The logs are flooded with this warning when using mod_verto/mod_telnyx_rtc
Remove this comment, this is only a behavior in our module

2024-02-12 17:18 UTC, Elhodred commented
I know it won't solve the issue. I mentioned that during the meeting. It's going to reduce the timeframe the race condition can happen, but as long as we keep the fix to make webrtc registers faster (https://telnyx.atlassian.net/browse/ENGDESK-26930) the race condition will exists.

The problem was worst with the new release because the thread that takes care of the FSM for the gateways is way busier now because we delete the GWs when the user disconnects. Each connect/Disconnect will trigger a reloadxml and the GWs will be rescanned again. As soon as we have a couple hundred GWs is when we started to see the issue and the service degraded.

Please, see comments here https://telnyx.slack.com/archives/C06HPKZJ7PH/p1707512894296729 and here https://telnyx.atlassian.net/browse/ENGDESK-27648?focusedCommentId=320909

2024-02-13 10:04 UTC, dev-ryanc approved these changes

2024-02-13 11:02 UTC, baloeng approved these changes

2024-02-13 12:22 UTC, merged