Jira-engdesk-33564
team-telnyx/freeswitch pull request #316
Opened 2024-08-21 18:24 UTC by izzytelnyx

Map the internal freeswitch cause code to sip cause

2024-08-22 18:44 UTC, baloeng commented
Based branch should be development and not master

2024-08-23 17:10 UTC, dev-ryanc reviewed
Follow the convention of creating the PR, please fix the PR request title

2024-08-29 14:25 UTC, dev-ryanc requested changes

2024-08-29 14:25 UTC, dev-ryanc commented on src/mod/endpoints/mod_sofia/mod_sofia.c
> +				} else if ((cause > 0 && cause < 128) || switch_telnyx_is_custom_q850_code(cause)) {
Those custom Q850 errors are both from FS and Telnyx. Ideally this function to check for customq850 can be a part of switch_channel instead.

2024-08-29 17:10 UTC, dev-ryanc commented on src/switch_channel.c
> +		case SWITCH_CAUSE_SUCCESS:                  break;
Shift one tab back, case should be the same line with the switch statement

2024-08-29 17:10 UTC, dev-ryanc commented on src/mod/endpoints/mod_sofia/mod_sofia.c
> +				} else if ((cause > 0 && cause < 128) || switch_channel_is_custom_q850_code(cause) == SWITCH_TRUE) {
No need to explicitly compare to `SWITCH_TRUE`.

2024-08-30 18:33 UTC, dev-ryanc approved these changes
lgtm

2024-09-03 07:46 UTC, minhtuan1407-telnyx approved these changes

2024-09-03 15:04 UTC, merged